// DecideCalc Service Worker — PWA offline support
// v39: navigation/HTML requests are network-first so freshly deployed content
// always reaches users and search crawlers. Static assets stay cache-first.
const CACHE = 'decidecalc-v49';
const ASSETS = [
  '/',
  '/index.html',
  '/about.html',
  '/privacy.html',
  '/terms.html',
  '/contact.html',
  '/cookie-policy.html',
  '/404.html',
  '/blog/index.html',
  '/blog/blog.css',
  '/blog/emi-vs-sip-which-is-better-india.html',
  '/blog/how-much-health-insurance-need-india.html',
  '/blog/rent-or-buy-house-2026-india.html',
  '/blog/debt-snowball-vs-avalanche-india.html',
  '/blog/home-loan-balance-transfer-refinance-india.html',
  '/blog/credit-card-minimum-payment-payoff-india.html',
  '/blog/mutual-fund-expense-ratio-impact-india.html',
  '/blog/retirement-withdrawal-rate-india.html',
  '/blog/bond-yield-vs-ytm-india.html',
  '/blog/how-to-calculate-loan-interest.html',
  '/blog/gross-pay-vs-net-pay.html',
  '/blog/how-much-house-can-i-afford.html',
  '/blog/how-to-calculate-investment-return.html',
  '/blog/how-to-calculate-percentage-increase-and-decrease.html',
  '/blog/how-to-calculate-a-discount.html',
  '/blog/how-to-calculate-inflation-rate.html',
  '/blog/how-to-calculate-savings-rate.html',
  '/blog/apr-vs-apy.html',
  '/blog/401k-vs-roth-ira.html',
  '/blog/how-to-calculate-student-loan-interest.html',
  '/calculators/emi-calculator.html',
  '/calculators/sip-calculator.html',
  '/calculators/income-tax-calculator.html',
  '/calculators/rent-vs-buy.html',
  '/calculators/loan-vs-investment.html',
  '/calculators/retirement-calculator.html',
  '/calculators/fd-vs-mutual-fund.html',
  '/calculators/home-loan-eligibility.html',
  '/calculators/ppf-calculator.html',
  '/calculators/gratuity-calculator.html',
  '/calculators/compound-interest-calculator.html',
  '/calculators/job-switch-decision.html',
  '/calculators/salary-hike-negotiator.html',
  '/calculators/career-switch-roi.html',
  '/calculators/bmi-calculator.html',
  '/calculators/real-age-calculator.html',
  '/calculators/health-insurance-need.html',
  '/calculators/pregnancy-due-date.html',
  '/calculators/wedding-budget-planner.html',
  '/calculators/baby-cost-calculator.html',
  '/calculators/gst-calculator.html',
  '/calculators/fuel-cost-calculator.html',
  '/calculators/life-decision-scorer.html',
  '/calculators/age-calculator.html',
  '/calculators/date-difference-calculator.html',
  '/calculators/business-days-calculator.html',
  '/calculators/leap-year-checker.html',
  '/calculators/unit-converter.html',
  '/calculators/currency-converter.html',
  '/calculators/word-counter.html',
  '/calculators/case-converter.html',
  '/calculators/json-formatter.html',
  '/calculators/password-generator.html',
  '/calculators/percentage-calculator.html',
  '/calculators/cgpa-calculator.html',
  '/calculators/base64-tool.html',
  '/calculators/slug-generator.html',
  '/calculators/time-duration-calculator.html',
  '/calculators/fd-calculator.html',
  '/calculators/simple-interest-calculator.html',
  '/calculators/inflation-calculator.html',
  '/calculators/cagr-calculator.html',
  '/calculators/calorie-calculator.html',
  '/calculators/water-intake-calculator.html',
  '/calculators/ideal-weight-calculator.html',
  '/calculators/marks-percentage-calculator.html',
  '/calculators/lorem-ipsum-generator.html',
  '/calculators/number-to-words.html',
  '/calculators/markdown-to-html.html',
  '/calculators/rd-calculator.html',
  '/calculators/rule-of-72.html',
  '/calculators/random-number-generator.html',
  '/calculators/rent-affordability-calculator.html',
  '/calculators/nps-calculator.html',
  '/calculators/epf-calculator.html',
  '/calculators/ssy-calculator.html',
  '/calculators/hra-calculator.html',
  '/calculators/home-loan-comparison.html',
  '/calculators/brokerage-calculator.html',
  '/calculators/countdown-timer.html',
  '/calculators/financial-year-calculator.html',
  '/calculators/week-number-calculator.html',
  '/calculators/stamp-duty-calculator.html',
  '/calculators/professional-tax-calculator.html',
  '/calculators/sleep-calculator.html',
  '/calculators/body-fat-calculator.html',
  '/calculators/pace-calculator.html',
  '/calculators/password-strength-meter.html',
  '/calculators/jwt-decoder.html',
  '/calculators/uuid-generator.html',
  '/calculators/hash-generator.html',
  '/calculators/pregnancy-week-tracker.html',
  '/calculators/apy-calculator.html',
  '/calculators/scss-calculator.html',
  '/calculators/mortgage-calculator.html',
  '/calculators/debt-to-income-calculator.html',
  '/calculators/net-worth-calculator.html',
  '/calculators/esi-contribution-calculator.html',
  '/calculators/credit-utilization-calculator.html',
  '/calculators/emergency-fund-calculator.html',
  '/calculators/kvp-calculator.html',
  '/calculators/nsc-calculator.html',
  '/calculators/savings-goal-calculator.html',
  '/calculators/budget-50-30-20-calculator.html',
  '/calculators/student-loan-calculator.html',
  '/calculators/401k-calculator.html',
  '/calculators/ira-calculator.html',
  '/calculators/paycheck-calculator.html',
  '/calculators/mssc-calculator.html',
  '/calculators/pmay-clss-subsidy-calculator.html',
  '/calculators/debt-payoff-planner.html',
  '/calculators/credit-card-payoff-calculator.html',
  '/calculators/investment-fee-calculator.html',
  '/calculators/loan-refinance-calculator.html',
  '/calculators/retirement-withdrawal-calculator.html',
  '/calculators/bond-ytm-calculator.html',
  '/calculators/car-loan-calculator.html',
  '/tools/index.html',
  '/categories/index.html',
  '/how-it-works/index.html',
  '/categories/finance/index.html',
  '/categories/career/index.html',
  '/categories/health/index.html',
  '/categories/life/index.html',
  '/categories/business/index.html',
  '/categories/datetime/index.html',
  '/categories/converter/index.html',
  '/categories/text/index.html',
  '/categories/dev/index.html',
  '/categories/utility/index.html',
  '/categories/education/index.html',
  '/categories/unique/index.html',
  '/assets/css/main.css',
  '/assets/js/core.js',
  '/assets/js/layout.js',
  '/assets/js/tools.js',
  '/assets/js/calc-page.js',
  '/assets/js/finance-suite.js',
  '/assets/js/engagement.js',
  '/assets/js/toolkit.js',
  '/assets/js/ads.js',
  '/assets/js/consent.js',
  '/assets/img/decidecalc-mark.svg',
  '/assets/img/decidecalc-favicon.svg',
  '/assets/img/favicon-16x16.png',
  '/assets/img/favicon-32x32.png',
  '/assets/img/favicon-48x48.png',
  '/assets/img/apple-touch-icon.png',
  '/assets/img/icon-192.png',
  '/assets/img/icon-512.png',
  '/assets/img/logo.png',
  '/assets/img/icon-192.svg',
  '/assets/img/icon-512.svg',
  '/assets/img/og.png',
  ,
  '/assets/img/blog-credit-card-payoff.png',
  ,
  '/assets/img/blog/mutual-fund-expense-ratio-impact-india.webp',
  '/assets/img/blog/simple-interest-vs-compound-interest.webp',
  '/assets/img/blog/how-to-calculate-savings-rate.webp',
  '/assets/img/blog/how-to-calculate-inflation-rate.webp',
  '/assets/img/blog/how-to-calculate-percentage-increase-and-decrease.webp',
  '/assets/img/blog/how-to-calculate-investment-return.webp',
  '/assets/img/blog/how-to-calculate-loan-interest.webp',
  '/assets/img/blog/debt-snowball-vs-avalanche-india.webp',
  '/assets/img/blog/home-loan-balance-transfer-refinance-india.webp',
  '/assets/img/blog/retirement-withdrawal-rate-india.webp',
  '/assets/img/blog/bond-yield-vs-ytm-india.webp',
  '/assets/img/blog/gross-pay-vs-net-pay.webp',
  '/assets/img/blog/how-much-house-can-i-afford.webp',
  '/assets/img/blog/how-to-calculate-compound-interest.webp',
  '/assets/img/blog/how-to-calculate-a-discount.webp',
  '/assets/img/blog/apr-vs-apy.webp',
  '/assets/img/blog/401k-vs-roth-ira.webp',
  ,
  ,
  ,
      ,
  ,
  ,
  ,
  '/assets/img/blog/rent-or-buy-house-2026-india.webp',
  '/assets/img/blog/how-to-calculate-paycheck-from-salary.webp',
  '/assets/img/blog/how-to-calculate-mortgage-payment.webp',
  '/assets/img/blog/how-much-will-10000-grow-compound-interest.webp',
  '/assets/img/blog/how-much-health-insurance-need-india.webp',
  '/assets/img/blog/emi-vs-sip-which-is-better-india.webp',
  '/assets/img/blog/30-year-vs-15-year-mortgage.webp',
  '/assets/img/blog/how-to-calculate-car-payment.webp',
  '/assets/img/blog/how-much-motorcycle-can-i-afford.webp',
  '/assets/img/blog/should-you-finance-a-phone.webp',
  '/assets/img/blog/how-to-calculate-tip.webp',
  '/assets/img/blog/what-is-sales-tax-how-to-calculate.webp',
  '/assets/img/blog/how-to-calculate-take-home-pay.webp',
  '/assets/img/blog/how-to-pay-off-debt-fast.webp',
  '/assets/img/blog/how-to-calculate-student-loan-interest.webp',
  '/favicon.ico',
  '/site.webmanifest',
  '/browserconfig.xml',
  '/assets/js/dc-currency.js',
  '/calculators/auto-loan-calculator.html',
  '/calculators/used-car-loan-calculator.html',
  '/calculators/truck-loan-calculator.html',
  '/calculators/motorcycle-loan-calculator.html',
  '/calculators/scooter-loan-calculator.html',
  '/calculators/bike-loan-calculator.html',
  '/calculators/ev-loan-calculator.html',
  '/calculators/personal-loan-calculator.html',
  '/calculators/iphone-emi-calculator.html',
  '/calculators/phone-emi-calculator.html',
  '/calculators/laptop-emi-calculator.html',
  '/calculators/ipad-emi-calculator.html',
  '/calculators/tv-emi-calculator.html',
  '/calculators/appliance-emi-calculator.html',
  '/calculators/loan-payment-calculator.html',
  '/calculators/interest-calculator.html',
  '/calculators/debt-payoff-calculator.html',
  '/calculators/discount-calculator.html',
  '/calculators/tip-calculator.html',
  '/calculators/sales-tax-calculator.html',
  '/calculators/take-home-pay-calculator.html',
  '/blog/how-to-calculate-car-payment.html',
  '/blog/how-much-motorcycle-can-i-afford.html',
  '/blog/should-you-finance-a-phone.html',
  '/blog/how-to-calculate-tip.html',
  '/blog/what-is-sales-tax-how-to-calculate.html',
  '/blog/how-to-calculate-take-home-pay.html',
  '/blog/how-to-pay-off-debt-fast.html',
];

// Install — cache all static assets
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS).then(() => self.skipWaiting())));
});

// Activate — clean old caches
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))).then(() => self.clients.claim())));
});

// Fetch — static assets cache-first; HTML/navigations network-first (offline fallback)
const PRECACHED = new Set(ASSETS);
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.hostname === 'cdn.jsdelivr.net') {
    e.respondWith(fetch(e.request).then(res => {
      const clone = res.clone();
      caches.open(CACHE).then(c => c.put(e.request, clone));
      return res;
    }).catch(() => caches.match(e.request)));
    return;
  }
  const isHtml = e.request.mode === 'navigate' || (e.request.headers.get('accept') || '').includes('text/html');
  if (isHtml) {
    // Do not runtime-cache HTML. A navigation always uses the deployed
    // response; only the installation-time offline copy is a fallback.
    e.respondWith(fetch(e.request).catch(() => caches.match(e.request).then(c => c || caches.match('/index.html'))));
    return;
  }
  e.respondWith(caches.match(e.request).then(cached => {
    if (cached) return cached;
    return fetch(e.request).then(res => {
      if (res.ok && PRECACHED.has(url.pathname)) {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
      }
      return res;
    });
  }));
});
